# Generated by Django 3.0.7 on 2021-02-15 13:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('body', ckeditor.fields.RichTextField()),
                ('is_free', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
