# Generated by Django 3.0.7 on 2021-02-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptiontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='body',
        ),
    ]
