# Generated by Django 3.0.7 on 2021-02-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_subscription_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontext',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to='subscription.Subscription'),
        ),
    ]
