# Generated by Django 3.0.7 on 2021-02-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_en_gb',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_fi',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_pt',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_pt_br',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_en_gb',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_fi',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_pt',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_pt_br',
        ),
    ]
