# Generated by Django 3.0.7 on 2021-02-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20210219_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en_gb',
            field=models.CharField(max_length=200, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es',
            field=models.CharField(max_length=200, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_pt_br',
            field=models.CharField(max_length=200, null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en_gb',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_pt_br',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
    ]
