XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX
XXXXXXX
XXXXXXX
XXXXXXXX
    XXXX XXXXXXXX
    XXXXXXXX XXX XX X
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXX X XXXXXXXXXXXXX
        XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX XXX XXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX X XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXX X XXX X XXXXXXXXXXXXXX XXXXXX X XXXXXX
        XX X XX X XXXXXXXXXXXXXX X XXXXXXXXXX X XXXX
                XXXXXXXX XXXXX XXXXXX X
                    XXXXXX XXX XXX XX X XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
                X
        X X XX

        XXXXXXX X XXXXXXXX XXX XXXXXXXXX

        XX XX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX
        X XX XXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXX X
                XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXXX XXX XX XXXXXXX XXXXXX XXXXX XXX XXXXXXX XX XXXXXX XXXXXX XXXXX XXXXXX XXXXXXXX XXXX XXXX XXXXXXX
                XXX
            X

            XX XXXXXXXXX X
                XXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            X XXXX X
                XXX XXXXXXXXXXXXX
                XX XXXXXXXXXX X
                    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X X
                        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX X X XXX XXXXXXXXXX XXXXXXXX XXXX XXX XXXXXXX XX X
                        XXXXXXXXXXXXX X XXXXX XXXXX XXXXXXXXXXXXXX X XXXX
                X

                XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXXX XXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXX XXXXXXXX XXXX XXX XXXXXXX
                XXX
            X
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXX
    X
XXXXXXXXX
